# fly.toml app configuration file generated for manibot on 2023-08-09T22:19:30+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "manibot"
primary_region = "ams"

[build]
