version: 2.1

orbs:
  node: circleci/node@5.2.0
  codecov: codecov/codecov@4.0.1

workflows:
  test:
    jobs:
      - node/test:
          test-results-for: jest
          post-steps:
            - codecov/upload
