version: 2.1

orbs:
  node: circleci/node@5.2.0
  codecov: codecov/codecov@4.0.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install flyctl
          command: |
            curl -L https://fly.io/install.sh | sh
            echo 'export PATH="$HOME/.fly/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Deploy to Fly
          command: |
            source $BASH_ENV
            flyctl deploy --remote-only --config fly.toml --app manibot
      - run:
          name: Set release metadata
          command: |
            source $BASH_ENV
            flyctl secrets set \
              RELEASE_VERSION="circle-${CIRCLE_BUILD_NUM}" \
              GIT_SHA="${CIRCLE_SHA1}" \
              --app manibot

workflows:
  test:
    jobs:
      - node/test:
          name: test
          test-results-for: jest
          post-steps:
            - codecov/upload
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
